# Gitlab CI file
before_script:

stages:
  - build
  - test
  - deploy

initial:
  stage: build

  script:
    - sudo chown -R gitlab-runner $HOME/.bundle
    - sudo gem install bundle
    - bundle update
    - bundle install
    - bundle exec rake db:drop
    - bundle exec rake db:create
    - bundle exec rake db:migrate

test_frontend:
  stage: test

  script:
    - bundle exec rake teaspoon

test_backend:
  stage: test

  script:
    - bundle exec rake

deployement:
  stage: deploy

  script:
    - sudo gem install dpl
    - sudo dpl --provider=heroku --app=unisport --api-key=$HEROKU_PRODUCTION_API_KEY
    - "curl -X POST --data-urlencode 'payload={\"text\": \"Hey bitches, looks like a new version is online : <https://unisport.herokuapp.com/>\"}' https://hooks.slack.com/services/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"

  only:
    - master
