# Gitlab CI file
before_script:

stages:
  - build
  - test
  - deploy

initial:
  stage: build

  script:
    - sudo chown -R gitlab-runner $HOME/.bundle
    - sudo gem install bundle
    - bundle update
    - bundle install
    - bundle exec rake db:drop
    - bundle exec rake db:create
    - bundle exec rake db:migrate

test_frontend:
  stage: test

  script:
    - bundle exec rake teaspoon

test_backend:
  stage: test

  script:
    - bundle exec rake
