# Gitlab CI file
before_script:

stages:
  - build
  - test
  - deploy

initial:
  stage: build

  script:
    - sudo chown -R gitlab-runner $HOME/.bundle
    - sudo gem install bundle
    - bundle update
    - bundle install
    - bundle exec rake db:drop RAILS_ENV=test
    - bundle exec rake db:create RAILS_ENV=test
    - bundle exec rake db:migrate RAILS_ENV=test
    - bundle exec rake db:seed RAILS_ENV=test

test_frontend:
  stage: test

  script:
    - bundle exec rake teaspoon RAILS_ENV=test

test_backend:
  stage: test

  script:
    - bundle exec rake RAILS_ENV=test

deployement:
  stage: deploy

  script:
    - sudo gem install dpl
    - sudo dpl --provider=heroku --app=unisport --api-key=$HEROKU_PRODUCTION_API_KEY

  only:
    - master
