---
- :domain: abdn.ac.uk
  :name: University of Aberdeen
- :domain: aber.ac.uk
  :name: 'Aberystwyth University '
- :domain: abertay.ac.uk
  :name: University of Abertay Dundee
- :domain: anglia.ac.uk
  :name: Anglia Ruskin University
- :domain: arts.ac.uk
  :name: University of Arts
- :domain: aston.ac.uk
  :name: Aston University
- :domain: bangor.ac.uk
  :name: Bangor University
- :domain: bath.ac.uk
  :name: University of Bath
- :domain: bbk.ac.uk
  :name: Birkbeck College, University of London
- :domain: bcom.ac.uk
  :name: British College of Osteopathic Medicine
- :domain: bcu.ac.uk
  :name: Birmingham City University
- :domain: beds.ac.uk
  :name: University of Bedfordshire
- :domain: bham.ac.uk
  :name: University of Birmingham
- :domain: bournemouth.ac.uk
  :name: Bournemouth University
- :domain: brad.ac.uk
  :name: University of Bradford
- :domain: bris.ac.uk
  :name: University of Bristol
- :domain: brookes.ac.uk
  :name: Oxford Brookes University
- :domain: brooklands.ac.uk
  :name: Brooklands College
- :domain: brunel.ac.uk
  :name: Brunel University Uxbridge
- :domain: bton.ac.uk
  :name: University of Brighton
- :domain: buck.ac.uk
  :name: University of Buckingham
- :domain: bucks.ac.uk
  :name: Buckinghamshire New University
- :domain: cam.ac.uk
  :name: University of Cambridge
- :domain: canterbury.ac.uk
  :name: Canterbury Christ Church University
- :domain: cardiff.ac.uk
  :name: Cardiff University
- :domain: chester.ac.uk
  :name: University of Chester
- :domain: city.ac.uk
  :name: City University
- :domain: collyers.ac.uk
  :name: The College of Richard Collyer
- :domain: courtauld.ac.uk
  :name: Courtauld Institute of Art
- :domain: coventry.ac.uk
  :name: Coventry University
- :domain: cranfield.ac.uk
  :name: Cranfield University
- :domain: derby.ac.uk
  :name: University of Derby
- :domain: dmu.ac.uk
  :name: De Montfort University
- :domain: dundee.ac.uk
  :name: University of Dundee
- :domain: dur.ac.uk
  :name: University of Durham
- :domain: ed.ac.uk
  :name: University of Edinburgh
- :domain: esc.ac.uk
  :name: East Surrey College
- :domain: eselondon.ac.uk
  :name: European School of Economics
- :domain: essex.ac.uk
  :name: University of Essex
- :domain: ex.ac.uk
  :name: University of Exeter
- :domain: gcal.ac.uk
  :name: Glasgow Caledonian University
- :domain: gcu.ac.uk
  :name: Glasgow Caledonian University
- :domain: gla.ac.uk
  :name: University of Glasgow
- :domain: glam.ac.uk
  :name: University of Glamorgan
- :domain: glos.ac.uk
  :name: University of Gloucestershire
- :domain: gold.ac.uk
  :name: Goldsmiths College, University of London
- :domain: gre.ac.uk
  :name: University of Greenwich
- :domain: gsa.ac.uk
  :name: Glasgow School of Art
- :domain: herts.ac.uk
  :name: University of Hertfordshire
- :domain: heythrop.ac.uk
  :name: Heythrop College, University of London
- :domain: hope.ac.uk
  :name: Liverpool Hope University College
- :domain: hud.ac.uk
  :name: University of Huddersfield
- :domain: hull.ac.uk
  :name: University of Hull
- :domain: huron.ac.uk
  :name: Huron University
- :domain: hw.ac.uk
  :name: Heriot-Watt University
- :domain: ic.ac.uk
  :name: Imperial College London
- :domain: imperial.ac.uk
  :name: Imperial College London
- :domain: ioe.ac.uk
  :name: Institute of Education
- :domain: kcl.ac.uk
  :name: King's College London
- :domain: keele.ac.uk
  :name: Keele University
- :domain: kingston.ac.uk
  :name: Kingston University
- :domain: lamp.ac.uk
  :name: Lampeter University
- :domain: lancs.ac.uk
  :name: University of Lancaster
- :domain: lboro.ac.uk
  :name: Loughborough University
- :domain: le.ac.uk
  :name: University of Leicester
- :domain: leeds.ac.uk
  :name: University of Leeds
- :domain: lgu.ac.uk
  :name: London Guildhall University
- :domain: lincoln.ac.uk
  :name: University of Lincoln
- :domain: liv.ac.uk
  :name: University of Liverpool
- :domain: livjm.ac.uk
  :name: Liverpool John Moores University
- :domain: lmu.ac.uk
  :name: Leeds Metropolitan University
- :domain: lon.ac.uk
  :name: London Business School
- :domain: londonmet.ac.uk
  :name: London Metropolitan University
- :domain: lse.ac.uk
  :name: London School of Economics and Political Science
- :domain: lshtm.ac.uk
  :name: London School of Hygiene & Tropical Medicine
- :domain: man.ac.uk
  :name: University of Manchester
- :domain: manchester.ac.uk
  :name: University of Manchester
- :domain: mdx.ac.uk
  :name: Middlesex University
- :domain: mmu.ac.uk
  :name: The Manchester Metropolitan University
- :domain: napier.ac.uk
  :name: Napier University
- :domain: ncl.ac.uk
  :name: Newcastle University
- :domain: newport.ac.uk
  :name: Newport University
- :domain: northampton.ac.uk
  :name: University of Northampton
- :domain: nottingham.ac.uk
  :name: University of Nottingham
- :domain: ntu.ac.uk
  :name: Nottingham Trent University
- :domain: open.ac.uk
  :name: Open University
- :domain: ox.ac.uk
  :name: University of Oxford
- :domain: paisley.ac.uk
  :name: University of Paisley
- :domain: plymouth.ac.uk
  :name: University of Plymouth
- :domain: port.ac.uk
  :name: University of Portsmouth
- :domain: portsmouth-college.ac.uk
  :name: Portsmouth College
- :domain: qmc.ac.uk
  :name: Queen Mary's College
- :domain: qmw.ac.uk
  :name: Queen Mary and Westfield College
- :domain: qub.ac.uk
  :name: The Queen's University Belfast
- :domain: ram.ac.uk
  :name: Royal Academy of Music
- :domain: rca.ac.uk
  :name: Royal College of Art
- :domain: rcm.ac.uk
  :name: Royal College of Music
- :domain: rdg.ac.uk
  :name: University of Reading
- :domain: rfhsm.ac.uk
  :name: Royal Free Hospital School of Medicine
- :domain: rgu.ac.uk
  :name: The Robert Gordon University
- :domain: rhbnc.ac.uk
  :name: Royal Holloway and Bedford New College
- :domain: rhul.ac.uk
  :name: Royal Holloway, University of London
- :domain: richmond.ac.uk
  :name: 'Richmond University '
- :domain: roehampton.ac.uk
  :name: Roehampton University of Surrey
- :domain: salford.ac.uk
  :name: University of Salford
- :domain: sas.ac.uk
  :name: " School of Advanced Study"
- :domain: sbu.ac.uk
  :name: South Bank University
- :domain: schillerlondon.ac.uk
  :name: Schiller International University, London
- :domain: sghms.ac.uk
  :name: Saint George's Hospital Medical School
- :domain: shef.ac.uk
  :name: University of Sheffield
- :domain: shu.ac.uk
  :name: Sheffield Hallam University
- :domain: smu.ac.uk
  :name: Swansea Metropolitan University
- :domain: soas.ac.uk
  :name: School of Oriental and African Studies
- :domain: solent.ac.uk
  :name: Southampton Solent University
- :domain: soton.ac.uk
  :name: University of Southampton
- :domain: southport.ac.uk
  :name: Southport College
- :domain: southwales.ac.uk
  :name: University of South Wales
- :domain: ssees.ac.uk
  :name: School of Slavonic and East European Studies
- :domain: st-and.ac.uk
  :name: University of St. Andrews
- :domain: st-patricks.ac.uk
  :name: St.Patrick's International College
- :domain: staffs.ac.uk
  :name: Staffordshire University
- :domain: stir.ac.uk
  :name: University of Stirling
- :domain: strath.ac.uk
  :name: University of Strathclyde
- :domain: sunderland.ac.uk
  :name: University of Sunderland
- :domain: surrey.ac.uk
  :name: University of Surrey
- :domain: sussex.ac.uk
  :name: University of Sussex
- :domain: swan.ac.uk
  :name: Swansea University
- :domain: tcm.ac.uk
  :name: Trinity College of Music
- :domain: tees.ac.uk
  :name: University of Teesside
- :domain: trinity-cm.ac.uk
  :name: Trinity College Carmarthen
- :domain: tvu.ac.uk
  :name: Thames Valley University
- :domain: ucl.ac.uk
  :name: University College London
- :domain: uclan.ac.uk
  :name: University of Central Lancashire
- :domain: ucs.ac.uk
  :name: University Campus Suffolk
- :domain: uea.ac.uk
  :name: University of East Anglia
- :domain: uel.ac.uk
  :name: University of East London
- :domain: ukc.ac.uk
  :name: 'University of Kent '
- :domain: ulsop.ac.uk
  :name: School of Pharmacy
- :domain: ulst.ac.uk
  :name: University of Ulster
- :domain: umds.ac.uk
  :name: United Medical and Dental Schools
- :domain: unl.ac.uk
  :name: University of North London
- :domain: unn.ac.uk
  :name: University of Northumbria at Newcastle
- :domain: uwcm.ac.uk
  :name: University of Wales College of Medicine
- :domain: uwe.ac.uk
  :name: University of the West of England
- :domain: uwic.ac.uk
  :name: University of Wales Institute
- :domain: wales.ac.uk
  :name: University of Wales
- :domain: warwick.ac.uk
  :name: University of Warwick
- :domain: westminster.ac.uk
  :name: University of Westminster
- :domain: wimbledon.ac.uk
  :name: Wimbledon School of Art
- :domain: wlv.ac.uk
  :name: University of Wolverhampton
- :domain: worc.ac.uk
  :name: University of Worcester
- :domain: york.ac.uk
  :name: University of York
